folio-org/mod-organizations

- README.md
Need a first PR, to finalise [FOLIO-2562](https://issues.folio.org/browse/FOLIO-2562).
> FOLIO-2562 initial repo setup

- descriptors/ModuleDescriptor-template.json
- src/main/java/org/folio/util/ResourcePathResolver.java
[MODORG-4](https://issues.folio.org/browse/MODORG-4) - Restrict updates of Organization records based upon acquisitions unit
Restrict updates of Organization based upon the acquisitions unit memberships of the user and the acquisitions unit being assigned to the record.
* Acquisitions units are used to determine if a user can update the organization record
* Unit tests are updated
- Do …
> MODORG-4 - Restrict updates of Organization records based upon acquisitions unit

- descriptors/ModuleDescriptor-template.json
MODORG-4 - Restrict updates of Organization records based upon acqusitions unit
While …
> MODORG-4 - Restrict updates of Organization records based upon acqusitions unit

- descriptors/ModuleDescriptor-template.json
- ramls/organizations.raml
https://issues.folio.org/browse/MODORGSTOR-73
* added missed permission, updated interface version
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies …
> MODORGSTOR-73 missed permission, updated interface version

- NEWS.md
- descriptors/ModuleDescriptor-template.json
- pom.xml
https://issues.folio.org/browse/MODORG-7
* updated release notes
* added missed permission block
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies …
> MODORG-7 release 1.0.0

- Dockerfile
- Jenkinsfile
- pom.xml
https://issues.folio.org/browse/MODORG-15
* updated RMB up to 31.1.0
While it's helpful …
> MODORG-15 updated RMB up to 31.1.0

- NEWS.md
- descriptors/ModuleDescriptor-template.json
- pom.xml
[MODORG-14](https://issues.folio.org/browse/MODORG-14)
MODORG (mod-organizations) release
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies increase. …
> Tmp release 1.1.0

- pom.xml
https://issues.folio.org/browse/MODORG-17
* fixed logging
* rmb v31.1.4
While it's …
> MODORG-17 fix logging

- NEWS.md
- pom.xml
https://issues.folio.org/browse/MODORG-18
* updated release notes
While it's helpful for …
> MODORG-18 release 1.1.1

- NEWS.md
* move release notes v1.1.1 to master branch
> release 1.1.1 news.md

- pom.xml
- src/main/java/org/folio/config/ApplicationConfig.java
- src/main/java/org/folio/rest/impl/BaseApi.java
- src/main/java/org/folio/rest/impl/OrganizationApi.java
- src/main/java/org/folio/service/BaseService.java
- src/main/java/org/folio/service/organization/OrganizationStorageService.java
- src/main/java/org/folio/service/protection/AcqDesiredPermissions.java
- src/main/java/org/folio/service/protection/AcquisitionsUnitsService.java
- src/main/java/org/folio/service/protection/AcquisitionsUnitsServiceImpl.java
- src/main/java/org/folio/service/protection/ProtectionService.java
- src/main/java/org/folio/service/protection/ProtectionServiceImpl.java
- src/main/resources/log4j2.properties
- src/test/java/org/folio/rest/impl/ApiTestBase.java
- src/test/java/org/folio/rest/impl/MockAcqUnits.java
- src/test/java/org/folio/rest/impl/MockServer.java
- src/test/java/org/folio/rest/impl/OrganizationApiTest.java
- src/test/java/org/folio/rest/impl/TestEntities.java
* https://issues.folio.org/browse/MODORG-21
* updated rmb 32.1.0
While it's helpful for …
> MODORG-21 rmb 32.1.0

- NEWS.md
- pom.xml
https://issues.folio.org/browse/MODORG-20 …
> MODORG-20 Release 1.2.0

- PERSONAL_DATA_DISCLOSURE.md
While it's helpful for reviewers to help identify potential problems, ensuring that it's …
> [MODORG-22] - Add personal data disclosure form

- pom.xml
- src/main/java/org/folio/service/protection/ProtectionServiceImpl.java
- src/test/java/org/folio/rest/impl/ApiTestBase.java
- src/test/java/org/folio/rest/impl/OrganizationApiTest.java
https://issues.folio.org/browse/MODORG-26
* upgraded rmb version according to https://github.com/folio-org/raml-module-builder/blob/master/doc/upgrading.md#version-330
* upgrading http client out of scope of this PR
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment. …
> MODORG-26 bump up rmb version v33.0.0

- NEWS.md
- pom.xml
* https://issues.folio.org/browse/MODORG-25
* update release notes
While it's helpful …
> MODORG-25 Release 1.3.0

- pom.xml
https://issues.folio.org/browse/MODORG-30 …
> MODORG-30. Kiwi R3 2021 - Log4j vulnerability verification and correction

- NEWS.md
- pom.xml
https://issues.folio.org/browse/MODORG-33 …
> MODORG-33 Kiwi Hotfix 1.3.1

- src/main/java/org/folio/exception/ErrorCodes.java
- src/main/java/org/folio/service/organization/OrganizationStorageService.java
- src/test/java/org/folio/rest/impl/OrganizationApiTest.java
https://issues.folio.org/browse/MODORG-19 …
> MODORG-19. "Account number" must be unique for organization

- NEWS.md
- pom.xml
https://issues.folio.org/browse/MODORG-38
* updated release notes
While it's helpful for …
> MODORG-38 Lotus 2022 R1 module release 1.4.0

- descriptors/ModuleDescriptor-template.json
[UXPROD-2553](https://issues.folio.org/browse/UXPROD-2553)
[MODORGSTOR-121](https://issues.folio.org/browse/MODORGSTOR-121)
Should be merged after/together with [mod-organizations-storage #79](https://github.com/folio-org/mod-organizations-storage/pull/79)
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid …
> [MODORGSTOR-121] - Update acq-models and interface version

- pom.xml
https://issues.folio.org/browse/MODORG-41
*  RMB v34.1.0 update
While it's helpful for …
> MODORG-41 RMB v34.1.0 update

- NEWS.md
- pom.xml
https://issues.folio.org/browse/MODORG-40
Add release notes 1.5.0 for Morning Glory R2 release
> [MORDORG-40] Add release notes 1.5.0 for Morning Glory R2 2022

- NEWS.md
- pom.xml
While it's helpful for reviewers to help identify potential problems, ensuring that it's …
> [MODORG-44] - Release 1.6.0

- PULL_REQUEST_TEMPLATE.md
- src/main/java/org/folio/rest/impl/OrganizationApi.java
- src/main/java/org/folio/service/BaseService.java
- src/main/java/org/folio/service/organization/OrganizationStorageService.java
- src/main/java/org/folio/service/protection/AcquisitionsUnitsServiceImpl.java
- src/main/java/org/folio/service/protection/ProtectionServiceImpl.java
https://issues.folio.org/browse/MODORG-37
The logging commands of the module has been adjusted according to the document: https://wiki.folio.org/display/DD/Logging 
Ideally all the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, …
> [MODORG-37] - Logging improvement

- NEWS.md
- pom.xml
While it's helpful for reviewers to help identify potential problems, 
ensuring that it's safe …
> [MODORG-47] - Release v1.7.0

- ramls/organizations.raml
- src/main/java/org/folio/rest/impl/OrganizationApi.java
- src/main/java/org/folio/service/organization/OrganizationService.java
- src/main/java/org/folio/service/organization/OrganizationStorageService.java
Resolves: [MODORG-46](https://issues.folio.org/browse/MODORG-46) Update dependent raml-util …
> [MODORG-46] Update dependent raml-util

- Dockerfile
- Jenkinsfile
- pom.xml
https://issues.folio.org/browse/MODORG-49
While it's helpful for reviewers to help identify …
> [MODORG-49]-updated to java-17

- NEWS.md
- pom.xml
https://issues.folio.org/browse/MODORG-58
While it's helpful for reviewers to help identify …
> [MODORG-58] - Release v1.8.0

- descriptors/ModuleDescriptor-template.json
- ramls/banking_information.raml
- src/main/java/org/folio/config/ApplicationConfig.java
- src/main/java/org/folio/rest/impl/BankingInformationAPI.java
- src/main/java/org/folio/service/organization/BankingInformationService.java
- src/main/java/org/folio/service/organization/BankingInformationServiceImpl.java
- src/main/java/org/folio/service/organization/OrganizationStorageService.java
- src/main/java/org/folio/util/ResourcePathResolver.java
- src/test/java/org/folio/rest/impl/ApiTestBase.java
- src/test/java/org/folio/rest/impl/BankingInformationAPITest.java
- src/test/java/org/folio/rest/impl/MockServer.java
- src/test/java/org/folio/rest/impl/OrganizationApiTest.java
- src/test/java/org/folio/rest/impl/TestEntities.java
- src/test/java/org/folio/rest/impl/TestSuite.java
[MODORG-54](https://issues.folio.org/browse/MODORG-54) - Banking information fields edit and delete
especially as the number of inter-module and inter-team dependencies …
> [MODORG-54] - Added bankingInformation API

- pom.xml
[MODORG-56](https://issues.folio.org/browse/MODORG-56)
While it's helpful for reviewers to …
> [MODORG-56] - Update RMB and vertx to the latest version

- pom.xml
https://folio-org.atlassian.net/browse/MODORG-61
Inspired by: https://github.com/folio-org/raml-module-builder/pull/1146
> [MODORG-61] mod-organizations: Upgrade RAML Module Builder

- pom.xml
Upgrade to the latest folio-di-support
https://github.com/folio-org/folio-di-support/releases/tag/v2.1.0
Release notes: https://github.com/folio-org/folio-di-support/blob/v2.1.0/doc/RELEASE_NOTES.md
> MODORDERS-61. Update folio-di-support

- NEWS.md
- pom.xml
https://folio-org.atlassian.net/browse/MODORG-62 …
> [MODORG-62] - Release v1.9.0

- descriptors/ModuleDescriptor-template.json
https://folio-org.atlassian.net/browse/MODORG-63 …
> [MODORG-63] permission: organizations.acquisitions-units-assignments manage referenced but not defined

- NEWS.md
- descriptors/ModuleDescriptor-template.json
- pom.xml
Release ticket https://folio-org.atlassian.net/browse/MODORG-63 to declare missed acq unit permissions into Quesnelia v1.9.1
> [MODORG-63] Release Quesnelia v1.9.1

- NEWS.md
- descriptors/ModuleDescriptor-template.json
- pom.xml
> Tmp release 1.9.2

- NEWS.md
- pom.xml
https://folio-org.atlassian.net/browse/FOLIO-4102 …
> Release v2.0.0

- Dockerfile
- Jenkinsfile
- pom.xml
[[FOLIO-4202] Update to mod-organizations Java 21](https://folio-org.atlassian.net/browse/FOLIO-4202)
Update java and dependency versions
> [FOLIO-4202] Update to mod-organizations Java 21

- src/main/java/org/folio/rest/impl/BankingInformationAPI.java
- src/main/java/org/folio/rest/impl/OrganizationApi.java
[MODORG-34](https://folio-org.atlassian.net/browse/MODORG-34) - json schema for categories defines type string but folio actually requires UUID
Updated models
[mod-organizations-storage PR](https://github.com/folio-org/mod-organizations-storage/pull/134) - [acq-models PR](https://github.com/folio-org/acq-models/pull/516)
Ideally, all the PRs involved in …
> [MODORG-34] Updated models
